### PR TITLE
WIP: implemet dynamic port group creation/deletion

### PR DESCRIPTION
**Pull request by joker-at-work**
We're trying to migrate from pre-configured port-channels on our switches to automatically configuring port-channels based on irconic's portgroups.

### CODE REVIEW

**Comment by fwiesel** [comment]
We also need to tear-down the port-channel when the port is unplugged.
But only if, we created the port-channel dynamically.

We might mark the port-channel somehow. The description of the port-channel interface could be (ab-)used for that.

We could allocate the port-channel id dynamically, but I fear, that is fraught with problems

My current thinking goes along the line of configuring the port-channel id as a port-group property in ironic, which gets passed to the port-binding, and then we can configure that port-channel unconditionally.
This saves us also to query the port-channel membership of the interfaces, as we know it from the DB.

**Comment by joker-at-work** [comment]
tear-down is still on the TODO-list. I just wanted to make sure, I'm on the right track with this.

If we allocate the port-channel-id by hand, we need to make at least sure, that no-one enters the same port-channel-id for multiple port-groups. But since we're trying to migrate from "only known on the switch" over "some on the switch, some in ironic" to "only in  ironic", this might still be error-prone.

There are other TODOs in the code: What do we do, if there are already port-channels configured on interfaces, that we're told belong to the new port-channel? Should we remove them from their port-channel, because they're obviously misconfigured, because our single-source-of-through (ironic/our db) tells us it should be otherwise? Your comment seems to indicate, that we don't even look, if the ports are configured as expected. So should we ignore this type of problem?

**Comment by fwiesel** [comment]
I would say, the database should be the source of truth, as there we have ACID, so it is much easier to enforce constraints, as no two port-groups on a switch should have the same port-channel id.

Doing so on a switch with concurrent instances configuring the switch in parallel is quite error prone.

But I agree, that configuring it in the port-group is also less then satisfactory.

We could allocate the channel-id in the driver in the neutron-db on port binding.
Say, give it a range (e.g. 1000:2000), which is free for auto-allocation, and then it will pick one free.
The assumption being, that we give it a range which is free.

**Comment by fwiesel** [comment]
Ah, another point of avoiding reads from the switch aside of consistency problems is to lighten the load on the API of the switch.

**Comment by fwiesel** [comment]
I think, that is how it can work:

Give the driver range of channel-group ids for its own purpose.
On Port Binding:
- Check if the port(s) have a channel-id (this can be deactivated, if we have migrated everything)
- If not allocate an ID (unique for the switch out of the range), and assign the ID 
- Store the ID `binding_vif_details`

On unplug:
- If the id is within the "dynamic" range, remove the port from the channel

That way, the only way to mess up is, by configuring a range which overlaps the manually configured VLANs, but I think, that is manageable risk.

**Comment by joker-at-work** [comment]
Superseded by work of @sebageek.

**Pull request closed without merging**
